[package]
name = "musictag"
version = "0.1.0"
edition = "2024"

[dependencies]
id3 = "1.12"
symphonia = { version = "0.5", features = ["mp3", "isomp4", "aac", "alac", "flac", "vorbis", "wav"] }
walkdir = "2.5"
